### ISSUE TITLE
Does not work in a xml file

### ISSUE THREAD

**Issue by DaanSchuitmaker** [sushant3524/epoch-converter#1]
Is it possible to make this work for other document types like XML

**Comment by sushant3524** [comment]
Can you please provide me with some particular files for my clarity of the problem and testing purposes?

**Comment by sushant3524** [comment]
> Is it possible to make this work for other document types like XML

Can you please provide me with some particular files for my clarity of the problem and testing purposes?

**Comment by DaanSchuitmaker** [comment]
`<content>
  <PostChangeLog>
    <function>PostChangeLog</function>
    <ChangeLog>
      <UserID>***********</UserID>
      <DeviceID>FA954A84D674FAE</DeviceID>
      <EntryGUID>793FCA-50B-76D-FDB-3BC93E512</EntryGUID>
      <Status>Status</Status>
      <Information></Information>
      <Action>INSERT</Action>
      <DataItem>HOURLINE</DataItem>
      <Value1>2353</Value1>
      <Value2></Value2>
      <Value3>1644336660000</Value3> <---- EpochTime
      <Value4></Value4>
      <Value5>WORK</Value5>
      <Value6>WO-705165</Value6>
      <Value7>SV-020340</Value7>
      <Value8>Repair Hours</Value8>
      <Value9>7F49248AA44A5CD</Value9>
      <Value10></Value10>
      <Binary1>
        <HourUpload>
          <StartMileage></StartMileage>
          <FinishMileage></FinishMileage>
          <ChargeableMileage></ChargeableMileage>
          <Task></Task>
          <EveryWareStatus>Current</EveryWareStatus>
          <EveryWareModified>1644336643993</EveryWareModified>
        </HourUpload>
      </Binary1>
    </ChangeLog>
  </PostChangeLog>
  <currentStatus></currentStatus>
  <currentServiceReport>SV-020340</currentServiceReport>
  <geoLatitude>5******</geoLatitude>
  <geoLongitude>-1****</geoLongitude>
  <userName>********</userName>
</content>`

**Comment by sushant3524** [comment]
> Is it possible to make this work for other document types like XML

Hello @DaanSchuitmaker,
Sorry for the late response, as I have been a little busy for a while.

- I found out that this was because of a bug in the vscode API that I used in my Extension.

- So, I opened an issue in the vscode repository. [LINK](https://github.com/microsoft/vscode/issues/149318) _Notice that I have used a little bit of your example to demonstrate the bug_

- They have solved that bug now and I believe it will get updated with their next version release. 
- However, If you want that feature urgently you can download **Visual Studio Code Insiders**, the **extension is working seamlessly in XML files** there.
